// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/review.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReview) Reset() {
	*x = UserReview{}
	mi := &file_proto_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReview) ProtoMessage() {}

func (x *UserReview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReview.ProtoReflect.Descriptor instead.
func (*UserReview) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{0}
}

func (x *UserReview) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReview) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserReview) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateReviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      uint64                 `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReviewRequest) GetReviewId() uint64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *UpdateReviewRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateReviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetReviewByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewByProductRequest) Reset() {
	*x = GetReviewByProductRequest{}
	mi := &file_proto_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewByProductRequest) ProtoMessage() {}

func (x *GetReviewByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewByProductRequest.ProtoReflect.Descriptor instead.
func (*GetReviewByProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewByProductRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      uint64                 `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReviewRequest) GetReviewId() uint64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *DeleteReviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	User          *UserReview            `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_proto_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ReviewResponse) GetUser() *UserReview {
	if x != nil {
		return x.User
	}
	return nil
}

type ReviewListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*ReviewResponse      `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_proto_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewListResponse) GetReviews() []*ReviewResponse {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_proto_review_proto protoreflect.FileDescriptor

const file_proto_review_proto_rawDesc = "" +
	"\n" +
	"\x12proto/review.proto\x12\aproduct\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\n" +
	"UserReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\x7f\n" +
	"\x13CreateReviewRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\x9c\x01\n" +
	"\x13UpdateReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x04R\breviewId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\":\n" +
	"\x19GetReviewByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"K\n" +
	"\x13DeleteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x04R\breviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\xab\x01\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12'\n" +
	"\x04user\x18\x05 \x01(\v2\x13.product.UserReviewR\x04user\"G\n" +
	"\x12ReviewListResponse\x121\n" +
	"\areviews\x18\x01 \x03(\v2\x17.product.ReviewResponseR\areviews2\x82\x03\n" +
	"\rReviewService\x12D\n" +
	"\rGetAllReviews\x12\x16.google.protobuf.Empty\x1a\x1b.product.ReviewListResponse\x12W\n" +
	"\x14GetReviewByProductID\x12\".product.GetReviewByProductRequest\x1a\x1b.product.ReviewListResponse\x12E\n" +
	"\fCreateReview\x12\x1c.product.CreateReviewRequest\x1a\x17.product.ReviewResponse\x12E\n" +
	"\fUpdateReview\x12\x1c.product.UpdateReviewRequest\x1a\x17.product.ReviewResponse\x12D\n" +
	"\fDeleteReview\x12\x1c.product.DeleteReviewRequest\x1a\x16.google.protobuf.EmptyB\x05Z\x03/pbb\x06proto3"

var (
	file_proto_review_proto_rawDescOnce sync.Once
	file_proto_review_proto_rawDescData []byte
)

func file_proto_review_proto_rawDescGZIP() []byte {
	file_proto_review_proto_rawDescOnce.Do(func() {
		file_proto_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)))
	})
	return file_proto_review_proto_rawDescData
}

var file_proto_review_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_review_proto_goTypes = []any{
	(*UserReview)(nil),                // 0: product.UserReview
	(*CreateReviewRequest)(nil),       // 1: product.CreateReviewRequest
	(*UpdateReviewRequest)(nil),       // 2: product.UpdateReviewRequest
	(*GetReviewByProductRequest)(nil), // 3: product.GetReviewByProductRequest
	(*DeleteReviewRequest)(nil),       // 4: product.DeleteReviewRequest
	(*ReviewResponse)(nil),            // 5: product.ReviewResponse
	(*ReviewListResponse)(nil),        // 6: product.ReviewListResponse
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
}
var file_proto_review_proto_depIdxs = []int32{
	7, // 0: product.ReviewResponse.date:type_name -> google.protobuf.Timestamp
	0, // 1: product.ReviewResponse.user:type_name -> product.UserReview
	5, // 2: product.ReviewListResponse.reviews:type_name -> product.ReviewResponse
	8, // 3: product.ReviewService.GetAllReviews:input_type -> google.protobuf.Empty
	3, // 4: product.ReviewService.GetReviewByProductID:input_type -> product.GetReviewByProductRequest
	1, // 5: product.ReviewService.CreateReview:input_type -> product.CreateReviewRequest
	2, // 6: product.ReviewService.UpdateReview:input_type -> product.UpdateReviewRequest
	4, // 7: product.ReviewService.DeleteReview:input_type -> product.DeleteReviewRequest
	6, // 8: product.ReviewService.GetAllReviews:output_type -> product.ReviewListResponse
	6, // 9: product.ReviewService.GetReviewByProductID:output_type -> product.ReviewListResponse
	5, // 10: product.ReviewService.CreateReview:output_type -> product.ReviewResponse
	5, // 11: product.ReviewService.UpdateReview:output_type -> product.ReviewResponse
	8, // 12: product.ReviewService.DeleteReview:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_review_proto_init() }
func file_proto_review_proto_init() {
	if File_proto_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_proto_goTypes,
		DependencyIndexes: file_proto_review_proto_depIdxs,
		MessageInfos:      file_proto_review_proto_msgTypes,
	}.Build()
	File_proto_review_proto = out.File
	file_proto_review_proto_goTypes = nil
	file_proto_review_proto_depIdxs = nil
}
