// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/shipping/shipping.proto

package shippingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientName string                 `protobuf:"bytes,2,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *Address) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type GetDetailShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailShipmentRequest) Reset() {
	*x = GetDetailShipmentRequest{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailShipmentRequest) ProtoMessage() {}

func (x *GetDetailShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetDetailShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *GetDetailShipmentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShipmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Courier         string                 `protobuf:"bytes,2,opt,name=courier,proto3" json:"courier,omitempty"`
	ServiceType     string                 `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	DestinationCity string                 `protobuf:"bytes,4,opt,name=destination_city,json=destinationCity,proto3" json:"destination_city,omitempty"`
	Weight          int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Price           float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TrackingNumber  string                 `protobuf:"bytes,8,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	EstimatedDays   int32                  `protobuf:"varint,9,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	Address         *Address               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShipmentResponse) Reset() {
	*x = ShipmentResponse{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentResponse) ProtoMessage() {}

func (x *ShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentResponse.ProtoReflect.Descriptor instead.
func (*ShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShipmentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShipmentResponse) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *ShipmentResponse) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ShipmentResponse) GetDestinationCity() string {
	if x != nil {
		return x.DestinationCity
	}
	return ""
}

func (x *ShipmentResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ShipmentResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentResponse) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

func (x *ShipmentResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type CalculateCostShippingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginCity      string                 `protobuf:"bytes,1,opt,name=origin_city,json=originCity,proto3" json:"origin_city,omitempty"`
	DestinationCity string                 `protobuf:"bytes,2,opt,name=destination_city,json=destinationCity,proto3" json:"destination_city,omitempty"`
	PostalCode      string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Weight          int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateCostShippingRequest) Reset() {
	*x = CalculateCostShippingRequest{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCostShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCostShippingRequest) ProtoMessage() {}

func (x *CalculateCostShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCostShippingRequest.ProtoReflect.Descriptor instead.
func (*CalculateCostShippingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateCostShippingRequest) GetOriginCity() string {
	if x != nil {
		return x.OriginCity
	}
	return ""
}

func (x *CalculateCostShippingRequest) GetDestinationCity() string {
	if x != nil {
		return x.DestinationCity
	}
	return ""
}

func (x *CalculateCostShippingRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CalculateCostShippingRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CalculateCostShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courier       string                 `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateCostShippingResponse) Reset() {
	*x = CalculateCostShippingResponse{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCostShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCostShippingResponse) ProtoMessage() {}

func (x *CalculateCostShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCostShippingResponse.ProtoReflect.Descriptor instead.
func (*CalculateCostShippingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateCostShippingResponse) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *CalculateCostShippingResponse) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *CalculateCostShippingResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CalculateCostShippingResponse) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

type CalculateCostShippingListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Cost          []*CalculateCostShippingResponse `protobuf:"bytes,1,rep,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateCostShippingListResponse) Reset() {
	*x = CalculateCostShippingListResponse{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCostShippingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCostShippingListResponse) ProtoMessage() {}

func (x *CalculateCostShippingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCostShippingListResponse.ProtoReflect.Descriptor instead.
func (*CalculateCostShippingListResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateCostShippingListResponse) GetCost() []*CalculateCostShippingResponse {
	if x != nil {
		return x.Cost
	}
	return nil
}

var File_proto_shipping_shipping_proto protoreflect.FileDescriptor

const file_proto_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/shipping/shipping.proto\x12\bshipping\"\x8f\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0erecipient_name\x18\x02 \x01(\tR\rrecipientName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\"*\n" +
	"\x18GetDetailShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xcd\x02\n" +
	"\x10ShipmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acourier\x18\x02 \x01(\tR\acourier\x12!\n" +
	"\fservice_type\x18\x03 \x01(\tR\vserviceType\x12)\n" +
	"\x10destination_city\x18\x04 \x01(\tR\x0fdestinationCity\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0ftracking_number\x18\b \x01(\tR\x0etrackingNumber\x12%\n" +
	"\x0eestimated_days\x18\t \x01(\x05R\restimatedDays\x12+\n" +
	"\aaddress\x18\n" +
	" \x01(\v2\x11.shipping.AddressR\aaddress\"\xa3\x01\n" +
	"\x1cCalculateCostShippingRequest\x12\x1f\n" +
	"\vorigin_city\x18\x01 \x01(\tR\n" +
	"originCity\x12)\n" +
	"\x10destination_city\x18\x02 \x01(\tR\x0fdestinationCity\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\"\x99\x01\n" +
	"\x1dCalculateCostShippingResponse\x12\x18\n" +
	"\acourier\x18\x01 \x01(\tR\acourier\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\"`\n" +
	"!CalculateCostShippingListResponse\x12;\n" +
	"\x04cost\x18\x01 \x03(\v2'.shipping.CalculateCostShippingResponseR\x04cost2\xd4\x01\n" +
	"\x0fShippingService\x12S\n" +
	"\x11GetDetailShipment\x12\".shipping.GetDetailShipmentRequest\x1a\x1a.shipping.ShipmentResponse\x12l\n" +
	"\x15CalculateCostShipping\x12&.shipping.CalculateCostShippingRequest\x1a+.shipping.CalculateCostShippingListResponseB\"Z /internal/pb/shipping;shippingpbb\x06proto3"

var (
	file_proto_shipping_shipping_proto_rawDescOnce sync.Once
	file_proto_shipping_shipping_proto_rawDescData []byte
)

func file_proto_shipping_shipping_proto_rawDescGZIP() []byte {
	file_proto_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_proto_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipping_shipping_proto_rawDesc), len(file_proto_shipping_shipping_proto_rawDesc)))
	})
	return file_proto_shipping_shipping_proto_rawDescData
}

var file_proto_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_shipping_shipping_proto_goTypes = []any{
	(*Address)(nil),                           // 0: shipping.Address
	(*GetDetailShipmentRequest)(nil),          // 1: shipping.GetDetailShipmentRequest
	(*ShipmentResponse)(nil),                  // 2: shipping.ShipmentResponse
	(*CalculateCostShippingRequest)(nil),      // 3: shipping.CalculateCostShippingRequest
	(*CalculateCostShippingResponse)(nil),     // 4: shipping.CalculateCostShippingResponse
	(*CalculateCostShippingListResponse)(nil), // 5: shipping.CalculateCostShippingListResponse
}
var file_proto_shipping_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.ShipmentResponse.address:type_name -> shipping.Address
	4, // 1: shipping.CalculateCostShippingListResponse.cost:type_name -> shipping.CalculateCostShippingResponse
	1, // 2: shipping.ShippingService.GetDetailShipment:input_type -> shipping.GetDetailShipmentRequest
	3, // 3: shipping.ShippingService.CalculateCostShipping:input_type -> shipping.CalculateCostShippingRequest
	2, // 4: shipping.ShippingService.GetDetailShipment:output_type -> shipping.ShipmentResponse
	5, // 5: shipping.ShippingService.CalculateCostShipping:output_type -> shipping.CalculateCostShippingListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shipping_shipping_proto_init() }
func file_proto_shipping_shipping_proto_init() {
	if File_proto_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipping_shipping_proto_rawDesc), len(file_proto_shipping_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_proto_shipping_shipping_proto_depIdxs,
		MessageInfos:      file_proto_shipping_shipping_proto_msgTypes,
	}.Build()
	File_proto_shipping_shipping_proto = out.File
	file_proto_shipping_shipping_proto_goTypes = nil
	file_proto_shipping_shipping_proto_depIdxs = nil
}
